/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2021-05-27 11:03:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class community_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <title>함께 즐기는 바둑 플랫폼 Balook</title>\r\n");
      out.write("\r\n");
      out.write("    <meta name=\"title\" content=\"함께 즐기는 바둑 플랫폼 Balook\">\r\n");
      out.write("    <meta name=\"description\" content=\"함께 즐기는 바둑 플랫폼 Balook 입니다\">\r\n");
      out.write("\r\n");
      out.write("    <!-- og tag 넣기 -->\r\n");
      out.write("    <meta property=\"og:image\" content=\"./img/page/p2Uy3c.jpg\"> \r\n");
      out.write("    <meta property=\"og:title\" content=\"함께 즐기는 바둑 플랫폼 Balook\">\r\n");
      out.write("    <meta property=\"og:description\" content=\"함께 즐기는 바둑 플랫폼 Balook 입니다\">\r\n");
      out.write("\r\n");
      out.write("    <!-- favicon 넣기 -->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"./img/favicon/다운로드.png\">\r\n");
      out.write("\r\n");
      out.write("    <!-- css 연결 -->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/container.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/header.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/footer.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/communityBody.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- js 연결-->\r\n");
      out.write("    <script src=\"./js/menuBtn.js\" defer></script>\r\n");
      out.write("    <script src=\"./js/alert.js\" defer></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- 구글 폰트 연결-->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Nanum+Pen+Script&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- font awesome 연결-->\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/1d8780591f.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header>\r\n");
      out.write("      <div class=\"navbar\">\r\n");
      out.write("        <div class=\"navbar__logo\">\r\n");
      out.write("            <i class=\"fas fa-dice\"></i>\r\n");
      out.write("            <a href=\"./index.html\">balook</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <ul class=\"navbar__menu\">\r\n");
      out.write("            <li><a href=\"./index.html\">Home</a></li>\r\n");
      out.write("            <li><a href=\"./community.jsp\">Community</a></li>\r\n");
      out.write("            <li><a href=\"#\" onclick= \"tmpMessage()\">test</a></li>\r\n");
      out.write("            <li><a href=\"#\" onclick= \"tmpMessage()\">test2</a></li>\r\n");
      out.write("            <li><a href=\"#\" onclick= \"tmpMessage()\">test3</a></li>\r\n");
      out.write("        </ul> \r\n");
      out.write("        <ul class=\"navbar__links\">\r\n");
      out.write("            <li><a href=\"./signIn.jsp\">sign-in</a></li>\r\n");
      out.write("            <li><a href=\"./signUp.jsp\"><i class=\"fas fa-user-friends\"></i></i></a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"#\" class=\"navbar__toggleBtn\"><i class=\"fas fa-bars\"></i></a>    \r\n");
      out.write("      </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"communityContainer\">  \r\n");
      out.write("        <div class=\"div4Absolute\">\r\n");
      out.write("            <section class=\"communitySection\">\r\n");
      out.write("                <table>\r\n");
      out.write("                    <thead>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>번호</th>\r\n");
      out.write("                            <th>제목</th>\r\n");
      out.write("                            <th class=\"articleAuthor\">작성자</th>\r\n");
      out.write("                            <th >작성일</th>\r\n");
      out.write("                            <th>조회</th>\r\n");
      out.write("                            <th>추천</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>1</td>\r\n");
      out.write("                            <td class=\"articleTitle\" style=\"text-align: left;\">test 제목입니다 많은 이용 부탁드립니다.</td>\r\n");
      out.write("                            <td>허강혁</td>\r\n");
      out.write("                            <td>21.05.09 15:28</td>\r\n");
      out.write("                            <td>0</td>\r\n");
      out.write("                            <td>0</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>2</td>\r\n");
      out.write("                            <td class=\"articleTitle\" style=\"text-align: left;\">test 제목</td>\r\n");
      out.write("                            <td>test 작성자</td>\r\n");
      out.write("                            <td>test 작성일</td>\r\n");
      out.write("                            <td>0</td>\r\n");
      out.write("                            <td>0</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>3</td>\r\n");
      out.write("                            <td class=\"articleTitle\"style=\"text-align: left;\">test 제목</td>\r\n");
      out.write("                            <td>test 작성자</td>\r\n");
      out.write("                            <td>test 작성일</td>\r\n");
      out.write("                            <td>0</td>\r\n");
      out.write("                            <td>0</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                    </tbody>\r\n");
      out.write("                    <tfoot></tfoot>\r\n");
      out.write("                </table>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"pagenationBox\">\r\n");
      out.write("                    <ul class=\"pagenation\">\r\n");
      out.write("                        <li><a href=\"http://www.naver.com\">1</a></li>\r\n");
      out.write("                        <li><a href=\"http://www.naver.com\">2</a></li>\r\n");
      out.write("                        <li><a href=\"http://www.naver.com\">3</a></li>\r\n");
      out.write("                        <li><a href=\"http://www.naver.com\">4</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </section>\r\n");
      out.write("\r\n");
      out.write("            <aside class=\"communitySideBar\">\r\n");
      out.write("                <ul class=\"articleBoard\">\r\n");
      out.write("                    <li>전체 게시물</li>\r\n");
      out.write("                    <li>인기 게시물</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"board\">\r\n");
      out.write("                    <button class=\"sideBarBtn\" onclick= \"tmpMessage()\"> 글쓰기</button>\r\n");
      out.write("                    <button class=\"sideBarBtn\" onclick= \"tmpMessage()\"> 내 게시물</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </aside>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <footer>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"footerBox\">\r\n");
      out.write("            <div class=\"footerLogo\">\r\n");
      out.write("                <i class=\"fas fa-dice\"></i>\r\n");
      out.write("                <a href=\"./index.html\">balook</a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"footerMenu\">\r\n");
      out.write("                <li><a href=\"./index.html\">Home</a></li>\r\n");
      out.write("                <li><a href=\"./community.jsp\">Community</a></li>\r\n");
      out.write("                <li><a href=\"#\">test1</a></li>\r\n");
      out.write("                <li><a href=\"#\">test2</a></li>\r\n");
      out.write("                <li><a href=\"#\">test3</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            \r\n");
      out.write("            <button class=\"topButton\" onclick=\"topBtnAction()\">top</button>\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"footerTail\">\r\n");
      out.write("                <li><a href=\"#\" onclick= \"tmpMessage()\">개발자 소개</a></li>\r\n");
      out.write("                <li><a href=\"#\" onclick= \"tmpMessage()\">contact</a></li>\r\n");
      out.write("                <li><a href=\"#\" onclick= \"tmpMessage()\">광고 안내</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("            <p>Copyright 2021-2021 kanghyeok heo. all rights reserved.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
